from PyQt6 import QtCore, QtGui, QtWidgets



class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(654, 622)
        Dialog.setWindowTitle("Таблица умножения ")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 191, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.checkBoxHand = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxHand.setEnabled(True)
        self.checkBoxHand.setGeometry(QtCore.QRect(10, 20, 134, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxHand.setFont(font)
        self.checkBoxHand.setChecked(False)
        self.checkBoxHand.setObjectName("checkBoxHand")
        self.checkBoxTren = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxTren.setGeometry(QtCore.QRect(10, 50, 147, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxTren.setFont(font)
        self.checkBoxTren.setObjectName("checkBoxTren")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(230, 10, 191, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButtonP = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButtonP.setGeometry(QtCore.QRect(20, 20, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButtonP.setFont(font)
        self.radioButtonP.setObjectName("radioButtonP")
        self.radioButtonU = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButtonU.setGeometry(QtCore.QRect(19, 47, 51, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButtonU.setFont(font)
        self.radioButtonU.setChecked(True)
        self.radioButtonU.setObjectName("radioButtonU")
        self.radioButtonM = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButtonM.setGeometry(QtCore.QRect(90, 20, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)

        font.setWeight(75)
        self.radioButtonM.setFont(font)
        self.radioButtonM.setObjectName("radioButtonM")
        self.radioButtonD = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButtonD.setGeometry(QtCore.QRect(90, 50, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButtonD.setFont(font)
        self.radioButtonD.setObjectName("radioButtonD")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 102, 642, 628))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelA = QtWidgets.QLabel(self.layoutWidget)
        self.labelA.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelA.setFont(font)
        self.labelA.setObjectName("labelA")
        self.horizontalLayout.addWidget(self.labelA)
        self.lineEditA = QtWidgets.QSpinBox(self.layoutWidget)
        self.lineEditA.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditA.setFont(font)
        self.lineEditA.setMinimum(1)
        self.lineEditA.setObjectName("lineEditA")
        self.horizontalLayout.addWidget(self.lineEditA)
        self.labelA_3 = QtWidgets.QLabel(self.layoutWidget)
        self.labelA_3.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelA_3.setFont(font)
        self.labelA_3.setObjectName("labelA_3")
        self.horizontalLayout.addWidget(self.labelA_3)
        self.lineEditB = QtWidgets.QSpinBox(self.layoutWidget)
        self.lineEditB.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditB.setFont(font)
        self.lineEditB.setMinimum(1)
        self.lineEditB.setObjectName("lineEditB")
        self.horizontalLayout.addWidget(self.lineEditB)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelA_4 = QtWidgets.QLabel(self.layoutWidget)
        self.labelA_4.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelA_4.setFont(font)
        self.labelA_4.setObjectName("labelA_4")
        self.horizontalLayout_2.addWidget(self.labelA_4)
        self.lineEditC = QtWidgets.QSpinBox(self.layoutWidget)
        self.lineEditC.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditC.setFont(font)
        self.lineEditC.setMinimum(1)
        self.lineEditC.setObjectName("lineEditC")
        self.horizontalLayout_2.addWidget(self.lineEditC)
        self.labelA_5 = QtWidgets.QLabel(self.layoutWidget)
        self.labelA_5.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelA_5.setFont(font)
        self.labelA_5.setObjectName("labelA_5")
        self.horizontalLayout_2.addWidget(self.labelA_5)
        self.lineEditD = QtWidgets.QSpinBox(self.layoutWidget)
        self.lineEditD.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditD.setFont(font)
        self.lineEditD.setMinimum(1)
        self.lineEditD.setObjectName("lineEditD")
        self.horizontalLayout_2.addWidget(self.lineEditD)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.pushButtonResult = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonResult.setMinimumSize(QtCore.QSize(0, 90))
        self.pushButtonResult.setObjectName("pushButtonResult")
        self.horizontalLayout_3.addWidget(self.pushButtonResult)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget.setMinimumSize(QtCore.QSize(640, 420))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelA_2 = QtWidgets.QLabel(self.layoutWidget)
        self.labelA_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelA_2.setFont(font)
        self.labelA_2.setObjectName("labelA_2")
        self.horizontalLayout_4.addWidget(self.labelA_2)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 100))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(300, 90))
        self.pushButton.setMaximumSize(QtCore.QSize(400, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.labelA_2.setVisible(False)
        self.lineEdit.setVisible(False)
        self.pushButton.setVisible(False)
        self.retranslateUi(Dialog)
        self.checkBoxHand.clicked['bool'].connect(self.lineEditA.setEnabled) #type: ignore
        self.checkBoxHand.clicked['bool'].connect(self.lineEditC.setEnabled) #type: ignore
        self.checkBoxHand.clicked['bool'].connect(self.lineEditB.setEnabled) #type: ignore
        self.checkBoxHand.clicked['bool'].connect(self.lineEditD.setEnabled) #type: ignore
        self.checkBoxTren.clicked['bool'].connect(self.lineEdit.setVisible) # type:ignore
        self.checkBoxTren.clicked['bool'].connect(self.labelA_2.setVisible) # type:ignore
        self.checkBoxTren.clicked['bool'].connect(self.pushButton.setVisible) #type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox.setTitle(_translate("Dialog", "Режимы работы"))
        self.checkBoxHand.setText(_translate("Dialog", "Ручной режим "))
        self.checkBoxTren.setText(_translate("Dialog", "Режим тренажер"))
        self.groupBox_2.setTitle(_translate("Dialog", "Операция проверки"))
        self.radioButtonP.setText(_translate("Dialog", "+"))
        self.radioButtonU.setText(_translate("Dialog", "*"))
        self.radioButtonM.setText(_translate("Dialog", "-"))
        self.radioButtonD.setText(_translate("Dialog", "/"))
        self.labelA.setText(_translate("Dialog", "А="))
        self.labelA_3.setText(_translate("Dialog", "В="))
        self.labelA_4.setText(_translate("Dialog", "C="))
        self.labelA_5.setText(_translate("Dialog", "D="))
        self.pushButtonResult.setText(_translate("Dialog", "Результат"))
        self.labelA_2.setText(_translate("Dialog", "Пример ="))
        self.lineEdit.setText(_translate("Dialog", "5"))
        self.pushButton.setText(_translate("Dialog", "Проверить"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())