# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1044, 668)
        Form.setMinimumSize(QtCore.QSize(1044, 668))
        Form.setMaximumSize(QtCore.QSize(1044, 668))
        Form.setStyleSheet("")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1044, 668))
        self.label.setMinimumSize(QtCore.QSize(1044, 668))
        self.label.setPixmap(QtGui.QPixmap("login-cover.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(390, 190, 301, 321))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 253, 251);\n"
"border-radius: 15px;\n"
"padding: 5px;\n"
"opacity:;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(430, 270, 214, 125))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setMinimumSize(QtCore.QSize(210, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit.setMinimumSize(QtCore.QSize(210, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border: 1px solid rgb(24, 55, 255);\n"
"border-radius: 5px;\n"
"padding: 0 8px;\n"
"background: white;\n"
"selection-background-color: darkgray;")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setMinimumSize(QtCore.QSize(210, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(210, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border: 1px solid rgb(24, 55, 255);\n"
"border-radius: 5px;\n"
"padding: 0 8px;\n"
"background: white;\n"
"selection-background-color: darkgray;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.radioButton = QtWidgets.QRadioButton(parent=self.widget)
        self.radioButton.setStyleSheet("color: rgb(112, 112, 112);")
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        self.widget1 = QtWidgets.QWidget(parent=Form)
        self.widget1.setGeometry(QtCore.QRect(430, 420, 215, 25))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(parent=self.widget1)
        self.label_5.setMinimumSize(QtCore.QSize(61, 21))
        self.label_5.setStyleSheet("background-color: rgb(17, 88, 255);\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"color: white;\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(parent=self.widget1)
        self.label_6.setEnabled(True)
        self.label_6.setMinimumSize(QtCore.QSize(81, 0))
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("color: rgb(17, 88, 255);")
        self.label_6.setScaledContents(False)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Войти"))
        self.label_3.setText(_translate("Form", "Электронная почта *"))
        self.label_4.setText(_translate("Form", "Пароль"))
        self.radioButton.setText(_translate("Form", "Показать пароль"))
        self.label_5.setText(_translate("Form", "Войти"))
        self.label_6.setText(_translate("Form", "Забыли пароль?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
